Adds winprop preferredWidth and preferredWidthStep.
paperwm/PaperWM pull request #453
Opened 2022-12-25 04:47 UTC by jtaala

Adds user configurable window properties (settable in `user.js` for example) `preferredWidth` and `preferredWidthStep`.  These properties allow setting an initial window width in pixels OR as an integer (0, 1, 2, 3) which corresponds to the `useful window widths` that can be cycled through (with `3` being a special case for maximizing the window width).

See `README.md` changes in this PR for more details (under section `Winprops`).

`preferredWidthStep` property is especially useful for windows that always open to an undesired width (step).  For example both _alacritty_ and _xfce4-terminal_ open by default on PaperWM to the first width step (too narrow for my preferences)... so I always increase it to the next width step (and doing many times throughout the day is tiresome).

This approach builds on / extends (and relates to) #304.  I wouldn't say it fixes that PR(?) since it only addresses the width (and not the vertical height).

Thoughts and feedback welcome!

2022-12-28 23:23 UTC, jtaala commented
@Gelbana @tadfisher @ccope @smichel17  - here's another quick fix to review when someone has time.

We could even combine this functionality into one winprop `preferredWidth` and have it handle both pixel or ratio values (e.g. if value is <= 1, treat as ratio).

Thoughts?

2022-12-29 00:47 UTC, smichel17 requested changes
I think combining them into one setting is a good idea.

From the user's perspective, I think it's a simpler interface. I would suggest defining it as a string. 

This way, we keep the flexibility to add different units of measurement in the future, without complicating the interface further. The numerical behavior could be allowed but should be undocumented/undefined, since it would likely change if we added a new unit.

For the internal representation, it's easier to reason about when the property either exists or doesn't vs also having to handle the 3rd case of when both exist (this gets worse with additional units). The code itself isn't more complicated, but the chance of some other part of the code accidentally depending on the order of priority, or something like that, increases.

- For now, I think an internal representation as a number, with the fraction/pixel distinction you mentioned, is good. If more units are added, it would probably make sense to switch to an object with the shape `{ value: number, unit: string }`.

- I would suggest parsing the user input to the internal representation as soon as it is defined (i.e. in the `defwinprop` function).

2022-12-29 01:00 UTC, jtaala commented
> I think combining them into one setting is a good idea.
> 
> From the user's perspective, I think it's a simpler interface. I would suggest defining it as a string.
> 
> This way, we keep the flexibility to add different units of measurement in the future, without complicating the interface further. The numerical behavior could be allowed but should be undocumented/undefined, since it would likely change if we added a new unit.
> 
> For the internal representation, it's easier to reason about when the property either exists or doesn't vs also having to handle the 3rd case of when both exist (this gets worse with additional units). The code itself isn't more complicated, but it increases the chance of some other part of the code accidentally depending on the order of priority, or something like that.
> 
> * For now, I think an internal representation as a number, with the fraction/pixel distinction you mentioned, is good. If more units are added, it would probably make sense to switch to an object with the shape `{ value: number, unit: string }`.
> * I would suggest parsing the user input to the internal representation as soon as it is defined (i.e. in the `defwinprop` function).

Yep, this makes a lot of sense.  I hadn't considered other units, but yes that is a possibility.

If we make it a string input then there's really no reason why we can't parse units as part of that - e.g. like css `600px`, or `4em` etc. with the parsing like:

- if a unit is defined (e.g. `400px` or `10em`') then convert value into pixels (and normal >1 interpretation applies);
- if no unit is defined AND value is > 1 - treat as pixel value;
- else treat is as ratio value;

Does the above sound okay?

2022-12-29 01:16 UTC, smichel17 commented
- I think that sounds good. To nitpick, I could add the edge case: values below 0 are invalid and will be discarded.

- Just to clarify, I'm not suggesting you ought to actually add support for other units now (I mean, it's fine if you feel like it, but I think `px` and `%` will cover the vast majority of use cases).

- I don't think it covers *all possible* future use cases. That's a tall order. Fortunately, we can change the internal representation later if we need to, so covering *all possible* future use cases is not required. It doesn't even need to cover all present use cases; just the documented ones ;)
    - When I was retroactively trying to think of use cases to justify my gut-feeling that the width should be defined as a string, the one I came up with was something like a ratio, where the width would be based on the height (e.g. `8:5`).

2022-12-29 01:37 UTC, jtaala commented
Nitpicking is fine! (since I don't really like nits!).  I agree though - I'll update external to support `%` and `px` and update documentation for this.

One thing though - you'll note a few other PRs like #456 and #454  do use standard notation for ratios (0.5 as opposed to 50%)... my undergrad was actually mathematics so I prefer standard notation for ratios (but then again, I'm biased there); but I do like the fact that `px` and `%` and string input is more akin to css's approach there.

Not sure what you think about consistency for those other PRs.  Thoughts?

2022-12-29 02:06 UTC, smichel17 commented
I agree that consistency is good. I personally like standard notation. The "software engineer" part of my brain screams *ONLY ALLOW ONE WAY TO DO IT AND MAKE UNITS EXPLICIT*.

I'll sleep on it. As long as it's [parsed](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) to the internal representation right away, it's probably fine. I think it's only a question of, "Is there a more useful thing we could do with numeric inputs later?" It's easy to add support later; hard to remove it once people use it.

2022-12-29 04:47 UTC, jtaala commented
Thanks @smichel17!  See changes in latest commit in this PR.

Yes, this is a much cleaner approach.  Currently accepting `%` or `px` units - anything else (or no unit) will not do anything and write a warning to extension log.  Likewise for any value input <= 0 (or no value input given).

Please re-review.

2023-01-31 08:33 UTC, closed without merging