Set only the workspace with focus as active
paperwm/PaperWM pull request #464
Opened 2023-01-14 14:32 UTC by Lythenas

This will set only the currently focused workspace active. I.e. the border of the active window on all non-focused workspaces is dimmed. This helps see which monitor is currently focused.

Note: The try-catch is likely not necessary but I don't really know what I'm doing here^^ So I'm open to suggestions.

2023-01-14 22:20 UTC, jtaala commented on tiling.js
> +            const ws = workspaceManager.get_workspace_by_index(i);
maybe change this to `let` (moreso  convention, although `const` works here in this use case `let` is more appropriate).

2023-01-14 22:20 UTC, jtaala commented on tiling.js
> +    try {
my thoughts on the try catch: not really needed (although isn't hurting) - you already do a check on
```javascript
if (wm) {...
```

2023-01-14 23:13 UTC, jtaala commented
@Lythenas, I really like this PR btw - makes sense and does make it much easier to use with multi-monitors.  Good work!

We could also implement this as a user-selectable option in the PapermWM extension settings (in case others think this behaviour make depend on user preference).  

If this is the case, I'm happy to help implement it in extension settings (I'd vote for it be on by default).

2023-01-14 23:17 UTC, jtaala requested changes
Added a couple of suggested (small) changes in comments, e.g.

1. change `const ws =` to `let`;
2. remove the try/catch to simplify and make it more readable etc.

Just suggestions - any other thoughts anyone?

2023-01-15 11:04 UTC, Lythenas commented
I integrated your suggestions.

While a setting for this would certainly be possible, I personally don't think there is any downside to always activating it. But it changes previous behavior so maybe other users will want to disable it.

2023-01-15 11:27 UTC, jtaala commented
> I integrated your suggestions.
> 
> While a setting for this would certainly be possible, I personally don't think there is any downside to always activating it. But it changes previous behavior so maybe other users will want to disable it.

Yes, I would agree.  I guess if others request it as an option we could implement an option for them - I like it and also don't see a downside (feels like it should be the default behaviour anyway).

2023-01-15 11:30 UTC, jtaala approved these changes

2023-01-23 10:56 UTC, merged

2023-01-29 01:17 UTC, smichel17 commented
Agreed, no need for a setting here.