Remove Gnome tiling left/right shortcuts
paperwm/PaperWM pull request #518
Opened 2023-04-30 22:21 UTC by tlevani

Based on the discussion in #516 I added gnome 44 shortcut removal using the same `set-with-backup` bash function used for setting other recommended gnome-shell settings. I haven't researched if there are any unwanted consequences of disabling these shortcuts like this, but it seems to work fine for me. It would be great if someone else with this issue could also test this before merging. Also, the backup `restore-gnome-shell-settings-YYYY-MM-DD.sh` file was successfully created with the original values stored inside.

2023-05-02 18:15 UTC, Lythenas requested changes
I think setting the keybinds to empty is fine for the recommended settings.

Can you also add these settings to the list in the README? Under "Recommended Gnome Shell Settings". And mention that the default gnome keybindings clash with the default PaperWM keybindings.

2023-05-04 15:42 UTC, jtaala commented
Looks great @tlevani!

Question (for everyone), got a bit confused in my testing from `set-recommended-gnome-shell-settings.sh` [not applying settings if a restore file exists](https://github.com/paperwm/PaperWM/pull/518/files#diff-1f2ed945f06168492ef47f0468cd0c7b714af1b3962be302993b36bd44e4bedfL5-L8).

Basically, I ran the `set-recommended-gnome-shell-settings.sh` first to test and it worked fine and disabled the keybind clash  Then I reset the keybinds manually (in dconf) and ran the `install.sh` script and selected `y` for the recommended settings - but this time it didn't fix the keybind clash because a restore file already existed.

What do you think?  remove those lines so that whenever we run it it resets the settings?  To avoid overwriting original settings (with the PaperWM settings) when we rerun, we could just create a restore file IF a previous restore file doesn't exist.

Thoughts?

2023-05-04 17:18 UTC, Lythenas commented
Ah interesting. @jtaala I will open a separate issue for that since it doesn't really have anything to do with this PR.

2023-05-04 17:25 UTC, Lythenas approved these changes
Looks good to me now.

2023-05-04 20:23 UTC, merged