Warp pointer when switching to workspace
paperwm/PaperWM pull request #711
Opened 2023-11-25 10:39 UTC by Rutherther

Attempt to implement/fix https://github.com/paperwm/PaperWM/issues/704

When switching to workspace that is either already visible on non-focused monitor, or is restored from previous state to non-focused monitor, cursor stays in the old workspace.

This warps the cursor to the monitor of workspace the user is switching to.

I actually stumbled upon a code that warped the cursor in switchWorkspace, as I accidentally first went to the master branch, and it has code for warping cursor inside of switchWorkspace. So PaperWM did have this functionality before, I am not sure why it was removed.

2023-11-25 22:16 UTC, jtaala commented
Thanks @Rutherther!

Good attempt! and you're thinking is right here.

Although, unfortunately this adds a bug/regression where if you go into Gnome overview and click the second monitor, it will cause the cursor to be warped to the first monitor.

2023-11-25 22:49 UTC, jtaala requested changes
Thanks @Rutherther!

Good attempt! and you're thinking is right here.

Although, unfortunately this adds a bug/regression where if you go into Gnome overview and click the second monitor, it will cause the cursor to be warped to the first monitor.

As well as warping behaviour by simply move the mouse to another monitor (which is not wanted).

In short, although warping mouse pointer is what you want to do - it wouldn't go in `switchWorkspace` method (which is called whenever workspace focusing changes) - it should go into a higher level calling function (e.g. when you use your gnome keybinds) to isolate warping only under the circumstance you want it to occur.

2023-11-25 22:50 UTC, jtaala commented
It would be great if this change was all that was needed here - but it's a bit more involved.

Feel free to keep experimenting and getting familiar with the codebase to try this here.

I'll look at this when I can - although I don't use those gnome-keybinds and am working on a few other things atm.

2023-11-25 22:51 UTC, jtaala commented
I'll switch this to a draft in the meantime.

2023-11-26 08:36 UTC, Rutherther commented
> Although, unfortunately this adds a bug/regression where if you go into Gnome overview and click the second monitor, it will cause the cursor to be warped to the first monitor.
Ah, right, gnome treats that as the same workspace, that didn't occur to me. Alright, I will try to look into that soon.

2023-12-10 09:21 UTC, Rutherther commented
So sorry for taking so long, I have a lot of stuff going on right now, I think I will be able to look into it at the end of December.

2024-01-22 14:58 UTC, Rutherther commented
It's not just warping when clicked on monitor in the overview. I also found another bug. When I connect Wacom tablet, and map it to single monitor, I cannot get my cursor out of the monitor with mouse. It just warps back to the same monitor.

After I hopefully get around to this, this is something to test after it's reimplemented.

2024-02-03 20:22 UTC, Rutherther commented
I am sorry, I won't be able to continue with this in any foreseeable future. Closing this PR.

2024-02-03 20:22 UTC, closed without merging

2024-05-24 08:37 UTC, ankostis commented
Do you have any more feedback on the Wacom tablet issue?

2024-05-24 19:06 UTC, Rutherther commented
I am not sure. This issue was introduced only in this PR that I was unable to fix. If you are having this issue without using code from this PR that's likely different issue. I am not using PaperWM anymore, so I am unable to help.

2024-05-25 02:49 UTC, jtaala commented
> I am not sure. This issue was introduced only in this PR that I was unable to fix. If you are having this issue without using code from this PR that's likely different issue. I am not using PaperWM anymore, so I am unable to help.

Thanks @Rutherther for the reply!

I don't have a wacom tablet so can't progress or test this one.  If anyone has a wacom tablet and wants to jump in a get familiar with the codebase let us know!

Jay.

2025-06-25 19:06 UTC, schrieveslaach commented
@Rutherther, @jtaala, I'm using paperwm with the patch of this PR and I can report that the issue with the wacom tablet is still present on Gnome 43 (Debian based distro). However, on Arch with the most recent Gnome version (48), the patch works fine with and without Wacom tablet.

2025-06-25 19:12 UTC, schrieveslaach commented
@jtaala, it seems to me that @Rutherther isn't active on GitHub anymore when I look into its profile. What do you think is a good way to fix #704

2025-06-25 20:03 UTC, Rutherther commented
I am still somehow active on GitHub, but my interest in PaperWM has vanished, so I can't really help here anyway. :(

2025-06-26 22:41 UTC, jtaala commented
> @Rutherther, @jtaala, I'm using paperwm with the patch of this PR and I can report that the issue with the wacom tablet is still present on Gnome 43 (Debian based distro). However, on Arch with the most recent Gnome version (48), the patch works fine with and without Wacom tablet.

Hey @schrieveslaach.  Unfortunately, I'm no longer actively developing / working on PaperWM (see this issue https://github.com/paperwm/PaperWM/issues/980).

2025-07-05 20:33 UTC, schrieveslaach commented
@Rutherther, @jtaala, thanks for the heads up and sorry for bothering too much.

FYI: with #1045 I found a solution that fixes the setup (without extending PaperWM).